// Copyright 2026 GNOME X Contributors
// SPDX-License-Identifier: Apache-2.0

use crate::AppError;

/// Port: re-render and persist the currently-configured theme CSS.
///
/// The "current configuration" lives in GSettings (`tb-*` keys on the
/// `io.github.gnomex.GnomeX` schema plus the system interface schema).
/// Implementations read those keys, build a `ThemeSpec`, and route it
/// through [`ThemeWriter::write_gtk_css`](super::ThemeWriter::write_gtk_css)
/// so both `gtk-4.0/gtk.css` and `gtk-3.0/gtk.css` land on disk.
///
/// Primarily invoked by [`PacksUseCase::apply_pack`](crate::use_cases::PacksUseCase::apply_pack)
/// after restoring a pack's `gsettings_overrides`, so the newly-restored
/// `tb-*` values turn into visible CSS immediately without the caller
/// having to re-run the theme apply dance manually. Packs therefore
/// guarantee a GTK 3 + GTK 4 dual-CSS result (GXF-061) without bloating
/// the pack format with generated bytes — the spec is the source of
/// truth, and the trigger regenerates CSS from it on every apply.
///
/// Implementations should be idempotent and safe to call when no pack
/// has been applied; failures are the caller's concern and should be
/// logged rather than aborting the pack apply.
pub trait ThemeRenderTrigger: Send + Sync {
    /// Rebuild the GTK4 + GTK3 + Shell CSS from the current GSettings
    /// state and write them through the configured `ThemeWriter`.
    fn rerender(&self) -> Result<(), AppError>;
}
