// Copyright 2026 GNOME X Contributors
// SPDX-License-Identifier: Apache-2.0

//! Filesystem adapter for [`AppLauncherOverrides`] (GXF-051).
//!
//! Writes user-level `.desktop` overrides under
//! `~/.local/share/applications/` whose `Exec=` is prefixed with the
//! right environment variable(s) to force a particular HiDPI scale.
//!
//! The adapter is parameterised by:
//! - `user_apps_dir` — the directory we write overrides into.
//!   Typically `$XDG_DATA_HOME/applications` (or `~/.local/share/...`).
//! - `system_apps_dirs` — the read-only directories we search for the
//!   upstream `.desktop` file to clone. Typically
//!   `/usr/share/applications` + `/usr/local/share/applications`.
//!
//! Threading the dirs through the constructor rather than pulling
//! them from the environment keeps this unit-testable: the
//! integration tests in `crates/infra/tests/` point both at a
//! `tempfile::tempdir()`.

use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

use gnomex_app::ports::AppLauncherOverrides;
use gnomex_app::AppError;
use gnomex_domain::{DomainError, PerAppScaleOverride};

/// Marker comment embedded in every override we write. Used by
/// [`list_overrides`] to distinguish files GNOME X manages from
/// user-authored overrides.
const MARKER: &str = "# Generated by GNOME X (per-app scaling override). Safe to delete.";

pub struct DesktopAppLauncherOverrides {
    user_apps_dir: PathBuf,
    system_apps_dirs: Vec<PathBuf>,
}

impl DesktopAppLauncherOverrides {
    /// Constructor for production — reads dirs from the environment
    /// the same way the XDG spec recommends.
    pub fn new() -> Self {
        let user_apps_dir = user_applications_dir();
        let system_apps_dirs = system_applications_dirs();
        Self {
            user_apps_dir,
            system_apps_dirs,
        }
    }

    /// Testable constructor — inject arbitrary dirs.
    pub fn with_dirs(user_apps_dir: PathBuf, system_apps_dirs: Vec<PathBuf>) -> Self {
        Self {
            user_apps_dir,
            system_apps_dirs,
        }
    }

    fn target_path(&self, app_id: &str) -> PathBuf {
        self.user_apps_dir.join(format!("{app_id}.desktop"))
    }

    /// Find the upstream `.desktop` file for `app_id`. Searches the
    /// user dir first (so an existing user override can be built
    /// upon), then each system dir.
    fn locate_source(&self, app_id: &str) -> Option<PathBuf> {
        let filename = format!("{app_id}.desktop");
        let user_candidate = self.user_apps_dir.join(&filename);
        if user_candidate.exists() {
            return Some(user_candidate);
        }
        for dir in &self.system_apps_dirs {
            let p = dir.join(&filename);
            if p.exists() {
                return Some(p);
            }
        }
        None
    }
}

impl Default for DesktopAppLauncherOverrides {
    fn default() -> Self {
        Self::new()
    }
}

impl AppLauncherOverrides for DesktopAppLauncherOverrides {
    fn register_override(&self, spec: &PerAppScaleOverride) -> Result<(), AppError> {
        validate_app_id(&spec.app_id)?;
        let scale = spec.scale.as_f64();

        let source = self
            .locate_source(&spec.app_id)
            .ok_or_else(|| {
                AppError::Settings(format!(
                    "no upstream .desktop found for '{}' in user or system dirs",
                    spec.app_id
                ))
            })?;

        let contents = fs::read_to_string(&source)
            .map_err(|e| AppError::Settings(format!("read {source:?}: {e}")))?;

        let rewritten = rewrite_exec_lines(&contents, scale);

        fs::create_dir_all(&self.user_apps_dir)
            .map_err(|e| AppError::Settings(format!("mkdir {:?}: {e}", self.user_apps_dir)))?;

        let target = self.target_path(&spec.app_id);
        let mut file = fs::File::create(&target)
            .map_err(|e| AppError::Settings(format!("create {target:?}: {e}")))?;
        writeln!(file, "{MARKER}")
            .map_err(|e| AppError::Settings(format!("write {target:?}: {e}")))?;
        file.write_all(rewritten.as_bytes())
            .map_err(|e| AppError::Settings(format!("write {target:?}: {e}")))?;
        Ok(())
    }

    fn remove_override(&self, app_id: &str) -> Result<(), AppError> {
        validate_app_id(app_id)?;
        let path = self.target_path(app_id);
        if !path.exists() {
            return Ok(());
        }
        // Only remove if the file was written by us — safety net
        // against clobbering a user-authored override.
        let head = fs::read_to_string(&path).unwrap_or_default();
        if !head.starts_with(MARKER) {
            return Err(AppError::Settings(format!(
                "{path:?} was not written by GNOME X (marker missing); refusing to delete"
            )));
        }
        fs::remove_file(&path)
            .map_err(|e| AppError::Settings(format!("rm {path:?}: {e}")))?;
        Ok(())
    }

    fn list_overrides(&self) -> Result<Vec<String>, AppError> {
        if !self.user_apps_dir.exists() {
            return Ok(Vec::new());
        }
        let mut out = Vec::new();
        for entry in fs::read_dir(&self.user_apps_dir)
            .map_err(|e| AppError::Settings(format!("readdir {:?}: {e}", self.user_apps_dir)))?
        {
            let entry = match entry {
                Ok(e) => e,
                Err(_) => continue,
            };
            let path = entry.path();
            if path.extension().and_then(|s| s.to_str()) != Some("desktop") {
                continue;
            }
            let head = fs::read_to_string(&path).unwrap_or_default();
            if head.starts_with(MARKER) {
                if let Some(stem) = path.file_stem().and_then(|s| s.to_str()) {
                    out.push(stem.to_owned());
                }
            }
        }
        out.sort();
        Ok(out)
    }
}

/// Rewrite every `Exec=` line in a `.desktop` file to prepend the
/// requested scale env var(s). All non-`Exec` lines are kept
/// verbatim, preserving ordering, comments, and whitespace — this
/// matters because many `.desktop` files carry translated `Name[xx]`
/// strings we must not touch.
///
/// Detail: we *don't* split on `;` for TryExec/Exec values — the
/// spec allows arguments to contain escaped semicolons and we'd
/// rather be conservative than mangle an app's command line. Instead
/// we just prepend `env GDK_SCALE=<n> <original>`.
pub fn rewrite_exec_lines(contents: &str, scale: f64) -> String {
    // Format the scale integer-ish when possible (GDK_SCALE is int
    // but text-scaling-factor / force-device-scale-factor are floats).
    let int_scale = scale.max(1.0).round() as u32;
    let frac_scale = format!("{scale:.2}");

    let mut out = String::with_capacity(contents.len() + 64);
    for line in contents.split_inclusive('\n') {
        // Preserve the trailing newline (if any) that split_inclusive
        // leaves on the line.
        let (body, newline) = match line.strip_suffix('\n') {
            Some(b) => (b, "\n"),
            None => (line, ""),
        };
        let trimmed = body.trim_start();
        if let Some(rest) = trimmed.strip_prefix("Exec=") {
            // Preserve any leading whitespace, then rewrite.
            let indent = &body[..body.len() - trimmed.len()];
            // env GDK_SCALE=<i> GDK_DPI_SCALE=<f/i> <rest> --force-device-scale-factor=<f>
            // GDK_DPI_SCALE compensates for the integer GDK_SCALE so
            // text is not double-scaled; force-device-scale-factor is
            // Chromium's analogue.
            let dpi_compensate = scale / int_scale as f64;
            let rewritten = format!(
                "{indent}Exec=env GDK_SCALE={int_scale} GDK_DPI_SCALE={dpi_compensate:.3} {rest} --force-device-scale-factor={frac_scale}{newline}"
            );
            out.push_str(&rewritten);
        } else {
            out.push_str(line);
        }
    }
    out
}

fn validate_app_id(app_id: &str) -> Result<(), AppError> {
    if app_id.is_empty()
        || app_id.contains('/')
        || app_id.contains('\\')
        || app_id.starts_with('.')
        || app_id.contains(std::path::is_separator as fn(char) -> bool)
    {
        return Err(AppError::Domain(DomainError::InvalidAppId(app_id.into())));
    }
    Ok(())
}

fn user_applications_dir() -> PathBuf {
    if let Some(xdg) = std::env::var_os("XDG_DATA_HOME") {
        return PathBuf::from(xdg).join("applications");
    }
    if let Some(home) = std::env::var_os("HOME") {
        return Path::new(&home).join(".local/share/applications");
    }
    PathBuf::from(".local/share/applications")
}

fn system_applications_dirs() -> Vec<PathBuf> {
    let mut dirs = Vec::new();
    if let Some(xdg) = std::env::var_os("XDG_DATA_DIRS") {
        for part in std::env::split_paths(&xdg) {
            dirs.push(part.join("applications"));
        }
    }
    if dirs.is_empty() {
        dirs.push(PathBuf::from("/usr/local/share/applications"));
        dirs.push(PathBuf::from("/usr/share/applications"));
    }
    dirs
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rewrite_prefixes_exec_and_preserves_other_lines() {
        let input = "\
[Desktop Entry]
Name=Files
Name[fr]=Fichiers
Exec=nautilus --new-window %U
Icon=org.gnome.Nautilus
Type=Application
";
        let out = rewrite_exec_lines(input, 1.25);
        assert!(out.contains("Name=Files"));
        assert!(out.contains("Name[fr]=Fichiers"));
        assert!(out.contains("Icon=org.gnome.Nautilus"));
        assert!(
            out.contains("Exec=env GDK_SCALE=1 GDK_DPI_SCALE=1.250 nautilus --new-window %U --force-device-scale-factor=1.25"),
            "output did not contain prefixed exec:\n{out}"
        );
    }

    #[test]
    fn rewrite_does_not_touch_non_exec_lines_with_exec_in_body() {
        // A common `.desktop` field: `Comment=Execute ...`. Our line
        // detector must not match this.
        let input = "Comment=Execute a program\nExec=/bin/true\n";
        let out = rewrite_exec_lines(input, 1.5);
        assert!(out.contains("Comment=Execute a program\n"));
        assert!(out.contains("Exec=env GDK_SCALE=2"));
    }

    #[test]
    fn validate_app_id_rejects_path_traversal() {
        assert!(validate_app_id("../../etc/passwd").is_err());
        assert!(validate_app_id(".hidden").is_err());
        assert!(validate_app_id("").is_err());
        assert!(validate_app_id("org.gnome.Nautilus").is_ok());
    }
}
